# Generated by Django 3.2.9 on 2022-03-25 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_first_name', models.CharField(max_length=20)),
                ('user_second_name', models.CharField(max_length=20)),
                ('user_age', models.IntegerField()),
                ('user_email', models.CharField(max_length=50)),
                ('user_password', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'user_tb',
            },
        ),
    ]
