# Generated by Django 3.2.9 on 2022-03-25 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMain',
            fields=[
                ('admin_id', models.AutoField(default='', primary_key=True, serialize=False)),
                ('admin_email', models.CharField(max_length=50)),
                ('admin_password', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'admin_main',
            },
        ),
    ]
