# Generated by Django 3.2.9 on 2022-04-22 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(default='', max_length=50),
        ),
    ]
