# Generated by Django 4.0.3 on 2022-04-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=50)),
                ('video_genre', models.CharField(max_length=20)),
                ('video_description', models.CharField(max_length=200)),
                ('video_duration', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=20)),
                ('video_file', models.FileField(upload_to='uploaded_files/')),
            ],
            options={
                'db_table': 'upload_files',
            },
        ),
    ]
